-- :fennel:1651677321
local _local_1_ = require("base16-colorscheme")
local setup = _local_1_["setup"]
setup({base00 = "#161616", base01 = "#262626", base02 = "#393939", base03 = "#525252", base04 = "#FDFDFD", base05 = "#FAFAFA", base06 = "#FFFFFF", base07 = "#c1c7cd", base08 = "#dde1e6", base09 = "#f2f4f8", base0A = "#42be65", base0B = "#3ddbd9", base0C = "#33b1ff", base0D = "#ff7eb6", base0E = "#be95ff", base0F = "#3ddbd9"})
vim.cmd("hi MatchParen gui=underline guibg=#262626")
vim.cmd("hi StatusNormal gui=underline guifg=#393939")
vim.api.nvim_set_hl(0, "StatusCommand", {link = "StatusNormal"})
vim.api.nvim_set_hl(0, "Vertsplit", {fg = "#161616"})
vim.cmd("hi Todo gui=bold guifg=#42be65")
vim.cmd("hi TSSymbol gui=bold guifg=#3ddbd9")
vim.cmd("hi TSFunction gui=bold guifg=#ff7eb6")
vim.api.nvim_set_hl(0, "rainbowcol1", {fg = "#878d96"})
vim.api.nvim_set_hl(0, "rainbowcol2", {fg = "#a8a8a8"})
vim.api.nvim_set_hl(0, "rainbowcol3", {fg = "#8d8d8d"})
vim.api.nvim_set_hl(0, "rainbowcol4", {fg = "#a2a9b0"})
vim.api.nvim_set_hl(0, "rainbowcol5", {fg = "#8f8b8b"})
vim.api.nvim_set_hl(0, "rainbowcol6", {fg = "#ada8a8"})
vim.api.nvim_set_hl(0, "rainbowcol7", {fg = "#878d96"})
vim.api.nvim_set_hl(0, "NvimTreeImageFile", {fg = "#33b1ff"})
vim.api.nvim_set_hl(0, "NvimTreeFolderIcon", {fg = "#525252"})
vim.cmd("hi NvimTreeSpecialFile gui=bold guifg=#33b1ff")
vim.api.nvim_set_hl(0, "NvimTreeIndentMarker", {fg = "#262626"})
vim.api.nvim_set_hl(0, "NvimTreeFolderName", {fg = "#393939"})
vim.api.nvim_set_hl(0, "NvimTreeEmptyFolderName", {fg = "#be95ff"})
vim.cmd("hi NvimTreeOpenedFolderName gui=bold guifg=#be95ff")
vim.cmd("hi CmpItemAbbrMatch gui=bold guifg=#FAFAFA")
vim.api.nvim_set_hl(0, "CmpItemAbbrMatchFuzzy", {fg = "#FAFAFA"})
vim.api.nvim_set_hl(0, "CmpItemAbbr", {fg = "#a8a8a8"})
vim.api.nvim_set_hl(0, "CmpItemKindVariable", {fg = "#be95ff"})
vim.api.nvim_set_hl(0, "CmpItemKindMethod", {fg = "#ff7eb6"})
vim.api.nvim_set_hl(0, "CmpItemKindKeyword", {fg = "#33b1ff"})
vim.api.nvim_set_hl(0, "CmpItemKindInterface", {link = "CmpItemKindVariable"})
vim.api.nvim_set_hl(0, "CmpItemKindText", {link = "CmpItemKindVariable"})
vim.api.nvim_set_hl(0, "CmpItemKindProperty", {link = "CmpItemKindKeyword"})
vim.api.nvim_set_hl(0, "CmpItemKindUnit", {link = "CmpItemKindKeyword"})
vim.api.nvim_set_hl(0, "CmpItemKindFunction", {link = "CmpItemKindMethod"})
vim.api.nvim_set_hl(0, "StatusLine", {fg = "#393939", bg = "#161616"})
vim.api.nvim_set_hl(0, "StatusLineNC", {fg = "#525252", bg = "#161616"})
vim.api.nvim_set_hl(0, "StatusReplace", {fg = "#161616", bg = "#dde1e6"})
vim.api.nvim_set_hl(0, "StatusInsert", {fg = "#161616", bg = "#3ddbd9"})
vim.api.nvim_set_hl(0, "StatusVisual", {fg = "#161616", bg = "#ff7eb6"})
return vim.api.nvim_set_hl(0, "StatusTerminal", {fg = "#161616", bg = "#be95ff"})